services:
  api:
    build: ./api
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/webhooks
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydb'
      - 'POSTGRES_PASSWORD=webhook'
      - 'POSTGRES_USER=tega'
    ports:
      - '5432'
