services:
#  api:
#    build:
#      context: ./api
#      dockerfile: Dockerfile
#    container_name: api
#    ports:
#      - "8080:8080"
#    environment:
#      - PG_USER=tega
#      - PG_PASSWORD=webhook
#      - PG_URL=jdbc:postgresql://db:5432/webhooks
#      - SPRING_RABBITMQ_HOST=rabbitmq
#      - SPRING_RABBITMQ_PORT=5672
#      - SPRING_RABBITMQ_USERNAME=guest
#      - SPRING_RABBITMQ_PASSWORD=guest
#    depends_on:
#      db:
#        condition: service_healthy
#      rabbitmq:
#        condition: service_healthy
#
#  worker:
#    build:
#      context: ./worker
#      dockerfile: Dockerfile
#    container_name: worker
#    environment:
#      - SPRING_RABBITMQ_HOST=rabbitmq
#      - SPRING_RABBITMQ_PORT=5672
#      - SPRING_RABBITMQ_USERNAME=guest
#      - SPRING_RABBITMQ_PASSWORD=guest
#    depends_on:
#      rabbitmq:
#        condition: service_healthy

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
#    healthcheck:
#      test: ["CMD", "rabbitmqctl", "status"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=webhooks
      - POSTGRES_PASSWORD=webhook
      - POSTGRES_USER=tega
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U tega -d webhooks"]
#      interval: 5s
#      timeout: 5s
#      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
      
volumes:
  postgres-data:
  redis-data:
