services:
#  api:
#    build: ./api
#    ports:
#      - "8080:8080"
#    environment:
#      - PG_USER=tega
#      - PG_PASSWORD=webhook
#      - PG_URL=jdbc:postgresql://db:5432/webhooks
#    volumes:
#      - ./api/src:/api/src
#      - ./api/pom.xml:/api/pom.xml
#      - ./api/mvnw:/api/mvnw
#      - ./.mvn:/.mvn
#    depends_on:
#      db:
#        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=webhooks
      - POSTGRES_PASSWORD=webhook
      - POSTGRES_USER=tega
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tega -d webhooks"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  postgres-data:
