spring:
  datasource:
    url: ${PG_URL}
    driver-class-name: org.postgresql.Driver
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    open-in-view: off
    hibernate:
      ddl-auto: none

  main:
    web-application-type: none
